
<?php $create = Mage::getBlockSingleton('giftwrap/adminhtml_sales_order_create_items')?>
<?php $newUrl = $this->getUrl('admingiftwrap/adminhtml_index/giftbox');?>
<?php $deleteUrl = $this->getUrl('admingiftwrap/adminhtml_index/deletegiftbox');?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
        <div class="form-buttons"><?php echo $this->getButtonsHtml() ?></div>
    </div>
	<button class="scalable" onclick="showEditForm('<?php echo $newUrl?>')" title="Create New Gift Box" type="button">
		<span>
			<span>Create New Gift Box</span>
		</span>
	</button>
<?php //var_dump(Mage::getSingleton('adminhtml/session_quote')->getQuote()->getId());?>	
<?php $gifboxcollection = $create->getGiftboxCollection();?>
	<div id="giftwrap-giftbox-additional" class="grid">	
	<?php if(count($gifboxcollection)):?>		
		<table class="data-table data order-tables" id="giftwrap-giftbox">
			<colgroup>				
				<col width="50">
				<col width="150">
				<col width="150">
				<col width="450">
				<col width="100">
				<col width="100">
				<col width="100">
				<col width="100">
			</colgroup>
			<thead>
				<tr class="headings">
					<th class="a-center no-link"><?php echo $this->__('No');?></th>
					<th class="a-center no-link"><?php echo $this->__('Paper');?></th>
					<th class="a-center no-link"><?php echo $this->__('Gift Card');?></th>
					<th class="a-center no-link"><?php echo $this->__('Items');?></th>
					<th class="a-center no-link"><?php echo $this->__('Unit Price');?></th>
					<th class="a-center no-link"><?php echo $this->__('Quantity');?></th>
					<th class="a-center no-link"><?php echo $this->__('Subtotal');?></th>
					<th class="a-center no-link"><?php echo $this->__('Action');?></th>
				</tr>
			</thead>
			<tbody class="even">
				<?php
				$i=1;
				foreach ($gifboxcollection as $giftbox): 
					$style=Mage::getModel('giftwrap/giftwrap')->load($giftbox->getStyleId());
					$giftcard=Mage::getModel('giftwrap/giftcard')->load($giftbox->getGiftcardId());
				?>
				<tr class="first">
					<td style="text-align:center">
						#<?php echo $i;?>
					</td>
					<td style="text-align:center">
					<li>
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftwrap/' . $style->getImage() ?>" width="75" height="75" />
					</li>
					<li >
					<?php echo $style->getTitle();?>
					</li>
					</td>
					<td  style="text-align:center">
					<?php if($giftcard->getId()){ ?>
					<li>
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftwrap/giftcard/' . $giftcard->getImage() ?>" width="75" height="75" />
					</li>
					<li >
					<?php echo $giftcard->getName();?>
					</li>
					<?php }?>
					</td>
					<td>
					<ul>
					<?php
					$its = $giftbox -> getItemCollection();
					$numberitems = 0;
					foreach ($its as $it){
						$itemId = $it->getItemId();
						$item=Mage::getModel('sales/quote_item')->load($itemId);
						$product=Mage::getModel('catalog/product')->load($item->getProductId());
						$qty = $it->getQty();
						$numberitems += $qty;
						?>
						<li><a href='<?php echo $product->getProductUrl(); ?>' ><?php echo  $item->getName(); ?> </a><?php echo ' - '.intval($qty).' item(s)'; ?> </li>
						<?php
					}
					if(Mage::getStoreConfig('giftwrap/general/amount_on_number_items')){
						$giftwrapAmount = floatval($numberitems)* (floatval($style->getPrice())+floatval($giftcard->getPrice()));
					}else{
						$giftwrapAmount = floatval($style->getPrice())+floatval($giftcard->getPrice());
					}
					?>
					</ul>
					</td>
					<!--<td><?php echo Mage::helper('core')->currency(floatval($style->getPrice())+floatval($giftcard->getPrice())) ; ?></td>-->
					<td  style="text-align:center"><?php echo Mage::helper('core')->currency($giftwrapAmount) ; ?></td>
					<td  style="text-align:center"><?php echo $giftbox->getQty();?></td>
					<td  style="text-align:center"><?php echo Mage::helper('core')->currency(floatval($giftwrapAmount) * floatval($giftbox->getQty())) ; ?></td>
					<td style="text-align:center">
						<a href="" onclick="showEditForm('<?php echo $newUrl?>', '<?php echo $giftbox->getId();?>','<?php if($giftbox->getGiftcardId()) echo $giftbox->getGiftcardId();?>');return false;"><?php echo $this->__('Edit'); ?></a>|
						<a href="" onclick="deleteGiftbox('<?php echo $deleteUrl?>','<?php echo $giftbox->getId();?>');return false;"><?php echo $this->__('Delete'); ?></a>
					</td>
				</tr>
				<?php $i++;?>
				<?php endforeach;?>
				
			</tbody>
		</table>
		<script type="text/javascript"> decorateTable('giftwrap-giftbox');</script>
	<?php endif; ?>
	</div>
    <?php echo $this->getChildHtml() ?>
</div>


