<?php
	$papers=$this->getAllPapers(); 
	
	$quote_id=Mage::getSingleton('checkout/cart')->getQuote()->getId();
	$id=Mage::app()->getRequest()->getParam('id');
	$giftbox=Mage::getModel('giftwrap/selection')->load($id);
	//Zend_Debug::dump($giftbox->getData());
	$item_id = Mage::app()->getRequest()->getParam('item_id');
    $_item = Mage::getModel('sales/quote_item')->load($item_id);
	$items = array();
    // if($item_id):
        // $items = $this->getCurrentItems(null,$item_id);
    // else :
        $items = $this->getAvailableItems($id);
    // endif;	
	$item_ids=$this->getItemIdsByGiftbox($id);
	$giftcardcollection=$this->getAllGiftcards();
	$maxItems = Mage::getStoreConfig('giftwrap/general/maximum_items_wrapall');
	$helper = Mage::helper('giftwrap');
	$helpIcon = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/giftwrap/fam_help.png';
	$_product = Mage::getModel('catalog/product')->load($_item->getProductId());
?>
<?php if($helper->checkUseCard()):?>
	<?php if(!$id):?>
		<div class="block-title"> 
			<h3><?php echo $this->__('Giftwrap for ')?>
				<a href='<?php echo $_product->getProductUrl(); ?>' ><?php echo Mage::getModel('catalog/product')->load($_item->getProductId())->getName() ?></a>
			</h3>
		</div>
		<div class="giftwrap-step">            
			<ul><li class="notice-msg" style="margin-bottom: 10px;text-align: left;">
				<?php echo $this->__('There are %s-item(s) of %s in your wrap.',$this->getNumberOfItemsCanWraped($_item,$id),Mage::getModel('catalog/product')->load($_item->getProductId())->getName())?>
			</li></ul>
            <p><?php echo $this->__(Mage::helper('giftwrap')->getNoteConfig('first'))?></p>
            <?php if(Mage::getStoreConfig('giftwrap/note/enable_note')||$helper->checkUseCard()):?>
			<p><?php echo $this->__(Mage::helper('giftwrap')->getNoteConfig('second'))?></p>
			<p><?php echo $this->__(Mage::helper('giftwrap')->getNoteConfig('third'))?></p>
            <?php endif;?>
			<p class="notice-end"><?php echo $this->__('You can hover your mouse over any');?> 
				<img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/>
			<?php echo $this->__('button for help.')?></p>
		</div>
	<?php else:?>
		<div class="block-title"> 
			<h3><?php echo $this->__('Edit Your Gift') ?></h3>
		</div>        
		<ul><li class="notice-msg" style="margin-bottom: 10px;text-align: left;">
		<p style="margin-bottom: 3px;"><?php echo $this->__('Items in your gift wrap:')?></p>
		 <?php
			$its = $giftbox->getItemCollection();
				$numberitems = 0;
				foreach ($its as $it) {
					$itemId = $it->getItemId();
					$item = Mage::getModel('sales/quote_item')->load($itemId);
					$product = Mage::getModel('catalog/product')->load($item->getProductId());
					$qty = $it->getQty();
					$numberitems += $qty;
					?>
					<p style="margin: 0 0 0 20px;"><a href='<?php echo $product->getProductUrl(); ?>' ><?php echo $item->getName(); ?> </a><?php echo ' - ' . intval($qty) . ' item(s)'; ?> </p>
					<?php
				}
			?>
		</li></ul>     
	<?php endif?>   
<?php else:?>
	<?php if(!$id):?>
		<div class="block-title"> 
			<h3><?php echo $this->__('Prepare Your Gift In 2 Simple Steps') ?></h3>
		</div>
		<div class="giftwrap-step">            
			<ul><li class="notice-msg" style="margin-bottom: 10px;text-align: left;">
				<?php echo $this->__('There are %s-item(s) of %s in your wrap.',$this->getNumberOfItemsCanWraped($_item,$id),Mage::getModel('catalog/product')->load($_item->getProductId())->getName())?>
			</li></ul>
            <p><?php echo $this->__(Mage::helper('giftwrap')->getNoteConfig('first'))?></p>
            <?php if(Mage::getStoreConfig('giftwrap/note/enable_note')||$helper->checkUseCard()):?>			
			<p><?php echo $this->__(Mage::helper('giftwrap')->getNoteConfig('third'))?></p>
            <?php endif;?>
			<p class="notice-end"><?php echo $this->__('You can hover your mouse over any');?> 
				<img style="margin-top:3px;" alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/>
			<?php echo $this->__('button for help.')?></p>
		</div>
	<?php else:?>
		<div class="block-title"> 
			<h3><?php echo $this->__('Edit Your Gift') ?></h3>
		</div>
		<ul><li class="notice-msg" style="margin-bottom: 10px;text-align: left;">
		<p style="margin-bottom: 3px;"><?php echo $this->__('Items in your gift wrap:')?></p>
         <?php
            $its = $giftbox->getItemCollection();
				$numberitems = 0;
				foreach ($its as $it) {
					$itemId = $it->getItemId();
					$item = Mage::getModel('sales/quote_item')->load($itemId);
					$product = Mage::getModel('catalog/product')->load($item->getProductId());
					$qty = $it->getQty();
					$numberitems += $qty;
					?>
					<p style="margin: 0 0 5px 20px;"><a href='<?php echo $product->getProductUrl(); ?>' ><?php echo $item->getName(); ?> </a><?php echo ' - ' . intval($qty) . ' item(s)'; ?> </p>
					<?php
				}
            ?>
		</li></ul>
	<?php endif?>   
<?php endif?>   
<br/>
<form id="giftwrap-form" action="<?php echo $this->getUrl('giftwrap/index/savegiftbox') ?>" method="post">		
    <div>
    <fieldset>
<?php if(count($papers)){?>
<?php 
	$text = '----- STEP 1: ';
	if($helper->checkUseCard()):
		$text = '----- STEP 1: ';
	else :
		$text = null;
	endif;
?>
<div class="fieldset" style="min-height:280px">
<h2 class="legend"><?php echo $this->__($text.'SELECT WRAPPING PAPER'); ?></h2><br/>
<div id="giftwrap-giftbox-paper-div" class="form-list">
	<div id="giftwrap-giftbox-paper-table">				
		
	<!--Slider for banner-->		
			<div id="slider-features">
				<div id="features-screen">				
						
						<ul id="images">																							
						<?php foreach($papers as $paper):?>	
								<li>
									<div class="item">
										<div class="product-info">
											<div class="featuredproduct-image"> 
												<a href="#" class="product-img">
													<label for="giftbox_paper_<?php echo $paper->getId();?>"><img src='<?php echo Mage::getBaseUrl('media').'giftwrap/'.$paper->getImage();?>' width="131" height="105" /></label>
												</a>										
											</div>
											<div class="featuredproduct-content">
												<div>
													<input type="radio" value="<?php echo $paper->getId(); ?>" <?php if($paper->getId()== $giftbox->getStyleId()){ ?> checked="checked" <?php }else{ ?>  <?php } ?> name="giftbox_paper" class="validate-one-required-by-name" id="giftbox_paper_<?php echo $paper->getId();?>" />
												</div>
												<h2><?php echo $paper->getTitle(); ?></h2>
												<div class="price-box">
                                                	<span class="regular-price">
										            	<span class="price"><?php echo Mage::helper('core')->currency($paper->getPrice()); ?></span>
										        	</span>
										        </div>											
																																													
											</div>
										</div>	
									</div>	
								</li>	
							<?php endforeach;?>
						</ul>
				</div>
			</div>		
		</div>
</div>
</div>

<?php }else{?>
<div class="mess-gift"><b><?php echo $this->__('No paper to select'); ?></b></div>
<?php }?>
<div class="clearer"></div>
<?php if($id):?>
    <div class="check-gift" id="check-gift" style="display:none">
<?php else :?>
    <div class="check-gift" id="check-gift">
<?php endif;?>
	<input type="checkbox" value="1" <?php if($giftbox->getGiftcardId() || $id){ ?> checked="checked" <?php }?> onclick="showGiftcardForm()" name="use_giftcard" id="use_giftcard" title = "Use Giftcard"/> 
	<label class="" for="use_giftcard">
		<?php if($helper->checkUseCard()):?>
			<?php echo $this->__('Proceed to Step 2 & 3')?>
		<?php else:?>
			<?php echo $this->__('Proceed to Step 2')?>
		<?php endif?>
	</label>
</div>
<div id="giftwrap-giftbox-giftcard-check">
<?php if(!Mage::getStoreConfig('giftwrap/general/use_card') && count($items) == 1): ?>
    <div id="giftwrap-giftbox-giftcard" style="display:none">
<?php else :?>
	<?php if(!$id):?>
    <div id="giftwrap-giftbox-giftcard" style="display:none">
	<?php else :?>
	<div id="giftwrap-giftbox-giftcard">
	<?php endif;?>
<?php endif;?>
<?php if($helper->checkUseCard()):?>
	<?php if(count($giftcardcollection)){?>
	<div class="fieldset" style="min-height: 430px">
	<h2 class="legend"><?php echo $this->__('----- STEP 2: CHOOSE A GIFT CARD'); ?></h2>
	<br/>
	<!-- div id="giftbox-giftcard-div"-->	
		<ul id="giftbox-giftcard" class="form-list">		
				<div id="view2">
					<ul id="images2">
						<li style="text-align:center;">
							<div class="item">
								<div class="product-info">
									<div class="featuredproduct-image"> 
                                        <label for="giftbox_giftcard_null" id="giftbox_giftcard_null_label">
											<img style="float:left;" src='' width="135" height="105" />
											<span style="float:left;margin-top:-90px;margin-left:10px;" class="no-card"><?php echo $this->__('No Card Item')?></span>
										</label>
									</div>
									<div class="featuredproduct-content">
										<div>
											<input type="radio" onclick="hideMessage()" value="0" <?php if($giftbox->getGiftcardId() == 0){ ?> checked="checked" <?php }else{ ?>  <?php } ?> name="giftbox_giftcard" class="validate-one-required-by-name" id="giftbox_giftcard_null" />
											<input type="hidden" id="max_len_null" value="0"/>			
										</div>
									</div>									
								</div>		
								<input type="hidden" name="gift-cart-tooltip" id="img-gift-null" value="0"/>
							</div>
							
						</li>
						<?php foreach($giftcardcollection as $giftcard):?>																					
							<li style="text-align:center;">
								<div class="item">
									<div class="product-info">
										<div class="featuredproduct-image"> 
											<a href="#" class="product-img" id="img-gift-<?php echo $giftcard->getId()?>">
												<label for="giftbox_giftcard_<?php echo $giftcard->getId();?>"><img src='<?php echo Mage::getBaseUrl('media').'giftwrap/giftcard/'.$giftcard->getImage();?>' width="135" height="105" />	</label>
											</a>
										</div>
										<div class="featuredproduct-content">
											<div>
												<input type="radio" onclick="checkMaxLen();viewMaxLen('<?php echo $giftcard->getCharacter()?>');" value="<?php echo $giftcard->getId(); ?>" <?php if($giftcard->getId()== $giftbox->getGiftcardId()){ ?> checked="checked" <?php }else{ ?>  <?php } ?> name="giftbox_giftcard" class="validate-one-required-by-name" id="giftbox_giftcard_<?php echo $giftcard->getId();?>" />
												<input type="hidden" id="max_len_<?php echo $giftcard->getId(); ?>" value="<?php echo $giftcard->getCharacter();?>"/>			
											</div>
											<h2><?php echo $giftcard->getName(); ?></h2>
											<div class="price-box">
												<span class="regular-price">
													<span class="price"><?php echo Mage::helper('core')->currency($giftcard->getPrice()); ?></span>
												</span>
											</div>
										</div>									
									</div>	
									<input type="hidden" name="gift-cart-tooltip" id="img-gift-<?php echo $giftcard->getId()?>" value="<?php echo $giftcard->getId(); ?>"/>
								</div>
								
							</li>
													
						<?php endforeach;?>
                           
					</ul>
				</div>
			
	<!--/div-->
	<?php if($giftbox->getGiftcardId()):?>
	<?php $giftcard = Mage::getModel('giftwrap/giftcard')->load($giftbox->getGiftcardId());?>
	<div id="text_message">
	<?php else :?>
	<div id="text_message" style="display:none">
	<?php endif;?>
	<label style="padding:10px" id="giftbox-message-label" for="giftcart-message-textarea"><?php echo $this->__('Your message. ('); ?>
		<strong id="giftcard-message-maxlen"><?php echo $giftcard->getCharacter()?></strong>
		<?php echo $this->__(' characters max)'); ?>
		<span id="help-message"><img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/></span>
	</label>
	<div class="input-box">
		<textarea name="giftbox_message" id="giftcart-message-textarea" onkeydown="checkMaxLen();" onkeyup="checkMaxLen()"  ><?php if($giftcard->getId()){ echo $giftbox->getMessage(); } ?></textarea>
	</div>
	</ul>
	</div>
	<?php }else{?>
	<div class="mess-gift"><b><?php echo $this->__('No giftcard to select'); ?></b></div>
	<?php }?>
<?php endif?>	
	<?php if(count($items)){?>
	<div class="fieldset" style="margin-top:40px; min-width: 90% !important; float:left;">
	<?php if(!$id):?>
		<?php if($helper->checkUseCard()):?>
			<h2 class="legend"><?php echo $this->__('----- STEP 3: CHOOSE OTHER PRODUCTS ON YOUR SHOPPING CART FOR WRAPPING'); ?></h5><br/>
		<?php else:?>
			<h2 class="legend"><?php echo $this->__('----- STEP 2: ADD OTHER ITEMS TO THIS GIFT'); ?></h5><br/>	
		<?php endif?>
		<?php else:?>	
		<?php if($helper->checkUseCard()):?>
			<h2 class="legend"><?php echo $this->__('----- STEP 3: EDIT YOUR GIFT ITEMS'); ?></h5><br/>
		<?php else:?>
			<h2 class="legend"><?php echo $this->__('----- STEP 3: EDIT YOUR GIFT ITEMS'); ?></h5><br/>	
		<?php endif?>
	<?php endif?>
	<br/>
	<ul id="giftbox-wraptype" class="form-list">
		<?php if(!$id):?>
			<li>
				<input type="radio" name="wrap_type" id="wrap_all" onclick="loadListProduct()" value="1" <?php if((!$giftbox->getId()) || ($giftbox->getType()==1) && !$id){?> checked="checked" <?php }?>/>
				<label for="wrap_all"><?php echo $this->__('Wrap this item only')?>
					<span id="help-item-1"><img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/></span>
				</label>
				
			</li>
			<li>
				<input type="radio" name="wrap_type" id="wrap_one" onclick="loadListProduct()" value="2" <?php if($giftbox->getType()==2 || $id){?> checked="checked" <?php }?> />
				<label for="wrap_one"><?php echo $this->__('Choose other products on your shopping cart for wrapping')?>
					<span id="help-item-2"><img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/></span>
				</label>		
			</li>
			<input id="hidden_item" type="hidden" name="hidden_item" value="<?php echo $item_id?>">
	<?php else:?>
        <li>
			<input style="display:none;" type="radio" name="wrap_type" id="wrap_one" value="2" <?php if($giftbox->getType()==2  || $id){?> checked="checked" <?php }?> />
			<label for="wrap_one"><?php echo $this->__('Choose other products on your shopping cart for wrapping')?>
				<span id="help-item-2"><img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/></span>
			</label>		
		</li>
    <?php endif;?>
	</ul>

	<div id="giftbox-item-div">

	<table class="data-table box-table giftwrap-style-table" id="giftwrap-giftbox-item" cellspacing="0">
		<thead>
			<tr>
				<th class="a-center"><?php echo $this->__('Item');?></th>
				<th class="a-center"><?php echo $this->__('Image');?></th>
				<th class="a-center"><?php echo $this->__('Price');?></th>
				<th class="a-center"><?php echo $this->__('Qty already wrapped / Total');?>
					<span id="help-wrapped-total">
						<img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/>
					</span>
				</th>
				<th class="a-center"><?php echo $this->__('Qty to be wrapped');?>
					<span id="help-qty-wrapped">
						<img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/>
					</span>
				</th>
				<th class="a-center"><?php echo $this->__('Tick to Wrap');?>
					<span id="help-tick">
						<img alt="<?php echo $this->__('Help')?>" src="<?php echo $helpIcon;?>"/>
					</span>
				</th>		
			</tr>
		</thead>
		<tbody>
			<?php $i=1;?>
			<?php foreach ($items as $ite):?>
				<?php
				$class=""; 
				
				$quote=Mage::getSingleton('checkout/session')->getQuote();
				$item=$quote->getItemById($ite);
				
				$options=Mage::helper('giftwrap')->getOptionList($item);
				$product=Mage::getModel('catalog/product')->load($item->getProductId());
				if($i%2==0){
					$class="even";
				}else{
					$class="odd";
				}
				if($i==1){
					$class.=" first";
				}else if($i==count($items)){
					$class.=" last";
				} 
				?>
				<tr class="<?php echo $class;?>">
					<td>
					<span class="product-name"><?php echo $item->getName();?></span>
					<?php if(count($options)){ ?>
						<dl class="item-options">
							<?php foreach ($options as $_option) : ?>
							<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
							<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
							<dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
								<?php if (isset($_formatedOptionValue['full_view'])): ?>
								<div class="truncated_full_value">
									<dl class="item-options">
										<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
										<dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
									</dl>
								</div>
								<?php endif; ?>
							</dd>
							<?php endforeach; ?>
						</dl>
					<?php 	} ?>
					</td>
					<td style="width:120px">
						<span class="img-small"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(66,53); ?>" width="66" height="53" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /></span>
					
					</td>
					<td>
						<span class="price"><?php echo Mage::helper('core')->currency($item->getPrice());?></span>
					</td>
					
					<td>
                            <?php if($id):?>
                            <span class='qty_wraped'><?php echo floatval($item->getQty())- floatval($this->getNumberCanWraped($item,$id));?></span>/<span class='qty_all'><?php echo $item->getQty();?></span>
                            <?php else:?>
                            <span class='qty_wraped'><?php echo floatval($this->getQtyWrap($item));?></span>/<span class='qty_all'><?php echo $item->getQty();?></span>
                            <?php endif;?>
                    </td>
					<td>
                    
							<?php if($id) $selectionItem = Mage::getModel('giftwrap/selectionitem')->loadBySelectionAndItem($id,$item->getId());?>
							<input type="hidden" name="qty_can_wrapped_<?php echo $item->getId()?>" id="qty_can_wrapped_<?php echo $item->getId()?>" value="<?php echo $this->getNumberOfItemsCanWraped($item,$id); ?>" />
							<?php if($item_id):?>
                            <input <?php if(!in_array($item->getId(), $item_ids) && $item_id != $item->getId()){?> disabled="disabled" <?php }?>  style="width:30px" type="text" name="qty_wrap_<?php echo $item->getId();?>" id="qty_wrap_<?php echo $item->getId();?>" value="<?php if($id && $selectionItem->getId()) {echo floatval($giftbox->getQty())*floatval($selectionItem->getQty());}else{ echo $this->getNumberOfItemsCanWraped($item,$id); }?>"/>
                            <?php else:?>
                            <input <?php if(!in_array($item->getId(), $item_ids)){?> disabled="disabled" <?php }?>  style="width:30px" type="text" name="qty_wrap_<?php echo $item->getId();?>" id="qty_wrap_<?php echo $item->getId();?>" value="<?php if($id && $selectionItem->getId()) {echo floatval($giftbox->getQty())*floatval($selectionItem->getQty());}else{ echo $this->getNumberOfItemsCanWraped($item,$id); }?>"/>
                            <?php endif;?>
                    </td>
					<td style="text-align:center;">
						<input type="checkbox" onclick="checkWrap(this,<?php echo $item->getId()?>)" value=<?php echo $item->getId(); ?> <?php if(in_array($item->getId(), $item_ids) || $item_id == $item->getId()){?> checked="checked" <?php } ?> class="" id="wrap-item-<?php echo $item->getId()?>"  name="wrap[]"/>
					</td>
				</tr>
				<?php $i++;?>
			<?php endforeach;?>
			
		</tbody>
	</table>
	</div>
	</div>
			<?php }else{?>
				<div class="mess-gift"><h4><?php echo $this->__('No item for wrapping.'); ?></h4></div>
			<?php }?>
</div>
</fieldset>
<input type="hidden" name="giftbox_quoteid" value="<?php echo $quote_id; ?>" />
<input type="hidden" name="giftbox_id" value="<?php echo $id; ?>" />
</div>
<?php if($id):?>
	<div class="actions-button">
	<?php else:?>
	<div class="actions-button" id="actions-button-id" style="display:none">
	<?php endif;?>
	<button id="close-giftbox" onclick="TINY.box.hide();return false;" class="button"><span><span><?php echo $this->__('Close')?></span></span></button>
	<button id="save-giftbox" onclick="return checkAll()" class="button" type="submit"><span><span><?php echo $this->__('Save')?></span></span></button>
	</div>
</div>
</form>
</div>
